### PR TITLE
Added several plugins

### PR DESCRIPTION
**Pull request by marianocarrazana**
Included zippyshare, solidfiles, and anothers images hosts(simples and sandboxes['continue...' forms]).

### CODE REVIEW

**Comment by poke** [comment]
Can you please rebase this against our current `master` branch? Most of the commits that are included in this PR are redundant.

**Comment by nmaier** [comment]
You reuse the get() function a lot, always similar. I wonder if it would make sense to generalize it a bit and make it a helper function available to all plugins.

Your sandbox plugins should always call `finish()`, whether you called `setURL` or not.

Also what @poke said, rebase please

**Comment by poke** [comment]
The `get` function itself doesn’t actually seem necessary since there is no recursion involved (so you could just have the code execute outside of the function).

But yeah, I agree that there is definitely a pattern in these plugins. Maybe we could expand the redirector or resolver plugin type to support posting data, so we could avoid having sandbox plugins for every of these sites.

**Comment by marianocarrazana** [comment]
@poke @nmaier ok, i will clean it

**Comment by poke** [comment]
Note that you do not need close this pull request and open a new one; you can just rebase your work locally, and then force-push to your fork (`git push --force`) to overwrite the branch in your fork and update this pull request. So you could recycle it with adjusted changes :)

**Pull request closed without merging**
